<?php

namespace App\Support\Editorial;

use App\Enums\BriefStatus;
use App\Enums\BriefTopicCategory;

class EditorialBriefCatalog
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public static function definitions(): array
    {
        return [
            [
                'title_suggestion' => 'Vücut Tipine Göre Üst Giyim Seçimi: Omuz, bel ve boy oranları',
                'topic_category' => BriefTopicCategory::StyleGuide,
                'target_audience' => 'Kendi stilini geliştirmek isteyen kadın ve erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Okuyucuya vücut oranlarını değiştirmeye çalışmadan, mevcut siluete uygun üst giyim kesimlerini seçmeyi öğreten pratik bir rehber. Marka önerisi veya ürün linki olmadan, omuz genişliği, gövde uzunluğu ve kalça hattına göre yaka ve kalıp tercihleri anlatılacak.',
                'subheadings' => "- Vücut tipi kavramını abartmadan ele almak\n- Omuz hattına göre yaka seçimi\n- Bel vurgusu ve kutu kesim dengesi\n- Uzun gövde için etek ve gömlek boyu\n- Deneme listesi ve ayna kontrolü",
                'suggested_internal_links' => "/yazilar\n/kategori/stil-rehberi",
                'cover_image_note' => 'Farklı kesim üst giyimlerin nötr arka planda karşılaştırmalı düzen çekimi; model yüzleri çeşitlendirilmeli',
                'planned_publish_date' => '2026-07-15',
                'status' => BriefStatus::Idea,
                'notes' => 'Beden utandırıcı dille yazılmamalı. Sağlık veya diyet tavsiyesi eklenmemeli.',
            ],
            [
                'title_suggestion' => 'Renk Uyumu Rehberi: Nötr tonlar, aksan renkler ve mevsimsel paletler',
                'topic_category' => BriefTopicCategory::StyleGuide,
                'target_audience' => 'Kombin yaparken renk seçiminde zorlanan okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Renk tekerleği temelleri ve günlük gardıropta uygulanabilir üç renk kuralı anlatılacak. Okuyucuya marka bağımlı olmayan, kendi dolabındaki parçalarla deneyebileceği örnekler sunulacak.',
                'subheadings' => "- Temel nötr renkler ve görevleri\n- Aksan rengi nasıl seçilir\n- Desen ve düz renk birlikteliği\n- Mevsimsel palet geçişleri\n- Sık yapılan renk hataları",
                'suggested_internal_links' => "/yazilar\n/kategori/stil-rehberi",
                'cover_image_note' => 'Renk kartelaları veya askıda nötr + aksan parça düzeni',
                'planned_publish_date' => '2026-07-22',
                'status' => BriefStatus::Preparing,
                'notes' => 'Trend rengi zorunlu kılmayan, zamansız bir çerçeve kullanılmalı.',
            ],
            [
                'title_suggestion' => 'Kumaş Türlerini Tanıma: Pamuk, keten, yün ve sentetik karışımlar',
                'topic_category' => BriefTopicCategory::StyleGuide,
                'target_audience' => 'Alışveriş öncesi etiket okumak isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Yaygın kumaş türlerinin dokusu, nefes alabilirliği, bakım ihtiyacı ve hangi parçalarda tercih edildiği sade dille açıklanacak. Doğrulanmamış çevresel iddialardan kaçınılacak.',
                'subheadings' => "- Doğal ve sentetik kumaş farkı\n- Mevsimsel kumaş seçimi\n- Etiket okuma pratiği\n- Bakım sembolleri özeti\n- Satın alma öncesi kontrol listesi",
                'suggested_internal_links' => "/yazilar\n/kategori/stil-rehberi",
                'cover_image_note' => 'Yakın plan kumaş dokusu kolajı',
                'planned_publish_date' => '2026-08-05',
                'status' => BriefStatus::Idea,
                'notes' => '“En iyi kumaş” gibi mutlak ifadeler kullanılmamalı.',
            ],
            [
                'title_suggestion' => 'Kıyafet Bakımı: Yıkama, kurutma ve depolama için temel kurallar',
                'topic_category' => BriefTopicCategory::StyleGuide,
                'target_audience' => 'Giysilerinin ömrünü uzatmak isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Parçaların formunu ve rengini korumak için yıkama sıcaklığı, kurutma yöntemi ve dolap düzeni önerileri. Ürün satışı veya marka övgüsü yok.',
                'subheadings' => "- Yıkama etiketi okuma\n- Renk aktarımını önleme\n- Kurutma ve ütüleme\n- Mevsimlik depolama\n- Onarım ve profesyonel temizlik ne zaman gerekir",
                'suggested_internal_links' => "/yazilar\n/kategori/stil-rehberi",
                'cover_image_note' => 'Düzenli dolap ve bakım malzemeleri flat lay',
                'planned_publish_date' => '2026-08-12',
                'status' => BriefStatus::Review,
                'notes' => 'Kimyasal karışım tarifleri verilmemeli.',
            ],
            [
                'title_suggestion' => 'Minimal Stil Oluşturma: Az parça ile tutarlı görünüm',
                'topic_category' => BriefTopicCategory::StyleGuide,
                'target_audience' => 'Sade gardırop kurmak isteyen şehirli okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Minimal stilin “az ve pahalı” olmak zorunda olmadığı anlatılarak, tekrar kombinlenebilir parça seçimi ve aksesuar disiplini işlenecek.',
                'subheadings' => "- Minimal stil ne demek değildir\n- Temel parça listesi\n- Tek renk paleti yaklaşımı\n- Aksesuar sınırı\n- Haftalık kombin planı",
                'suggested_internal_links' => "/yazilar\n/kategori/stil-rehberi",
                'cover_image_note' => 'Az parçalı nötr kombin, sade arka plan',
                'planned_publish_date' => '2026-08-26',
                'status' => BriefStatus::Idea,
                'notes' => 'Lüks marka referansı veya fiyat vurgusu yok.',
            ],
            [
                'title_suggestion' => 'Kapsül Gardırop Hazırlama: 30 parçayla 2 haftalık kombin planı',
                'topic_category' => BriefTopicCategory::WomensFashion,
                'target_audience' => 'Yoğun tempoda giyinen kadın okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Mevcut dolaptan kapsül gardırop çıkarma adımları ve iki haftalık örnek kombin matrisi. Yeni alışveriş baskısı yapılmadan önce envanter değerlendirmesi vurgulanacak.',
                'subheadings' => "- Envanter çıkarma\n- Temel parça kategorileri\n- Renk ve siluet uyumu\n- 14 günlük kombin tablosu\n- Eksik parça önceliklendirme",
                'suggested_internal_links' => "/yazilar\n/kategori/kadin-modasi",
                'cover_image_note' => 'Askıda düzenli kapsül parçaları',
                'planned_publish_date' => '2026-07-18',
                'status' => BriefStatus::Preparing,
                'notes' => 'Affiliate veya mağaza linki eklenmeyecek.',
            ],
            [
                'title_suggestion' => 'İş Görüşmesinde Sade Kombin: Kadınlar için profesyonel görünüm',
                'topic_category' => BriefTopicCategory::WomensFashion,
                'target_audience' => 'İş görüşmesine hazırlanan kadın profesyoneller',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Sektör farklarına kısa değinilerek, iş görüşmesinde dikkat dağıtmayan, temiz ve özenli kombin ilkeleri. Hukuki veya kariyer garantisi içermez.',
                'subheadings' => "- Sektöre göre kod esnekliği\n- Üst ve alt giyim dengesi\n- Ayakkabı ve çanta seçimi\n- Makyaj ve aksesuar sınırı\n- Son kontrol listesi",
                'suggested_internal_links' => "/yazilar\n/kategori/kadin-modasi",
                'cover_image_note' => 'Profesyonel ofis ortamında sade kombin',
                'planned_publish_date' => '2026-07-25',
                'status' => BriefStatus::Idea,
                'notes' => '“Mutlaka takım elbise” gibi katı kurallar yerine rehberlik tonu.',
            ],
            [
                'title_suggestion' => 'Gardırop Düzenleme: Adım adım sınıflandırma ve saklama',
                'topic_category' => BriefTopicCategory::WomensFashion,
                'target_audience' => 'Dolabını yeniden organize etmek isteyen kadın okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Giysileri kategori, mevsim ve kullanım sıklığına göre ayırma yöntemi. Satın alma önerisi değil, mevcut parçaların yönetimi.',
                'subheadings' => "- Çıkarma ve temizlik\n- Tut–bağış–tamir ayrımı\n- Askı ve katlama kuralları\n- Mevsimlik rotasyon\n- Sürdürülebilir bağış yönlendirmesi",
                'suggested_internal_links' => "/yazilar\n/kategori/kadin-modasi\n/kategori/surdurulebilir-moda",
                'cover_image_note' => 'Öncesi/sonrası dolap düzeni (abartılı stilizasyon yok)',
                'planned_publish_date' => '2026-08-08',
                'status' => BriefStatus::Review,
                'notes' => 'Tüketimi artıran “her şeyi at” mesajı verilmemeli.',
            ],
            [
                'title_suggestion' => 'Zamansız Parçalar: Kadın gardırobunda uzun ömürlü 12 temel',
                'topic_category' => BriefTopicCategory::WomensFashion,
                'target_audience' => 'Kaliteli temel parça arayan kadın okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Trendden bağımsız, yıllarca kombinlenebilecek 12 temel parça listesi ve her birinin neden işlevsel olduğu. Marka veya fiyat karşılaştırması yok.',
                'subheadings' => "- Zamansız parça tanımı\n- Üst giyim temelleri\n- Alt giyim temelleri\n- Dış giyim ve ayakkabı\n- Parça seçerken kalite ipuçları",
                'suggested_internal_links' => "/yazilar\n/kategori/kadin-modasi",
                'cover_image_note' => '12 parçalı flat lay düzeni',
                'planned_publish_date' => '2026-08-19',
                'status' => BriefStatus::Idea,
                'notes' => 'Liste kişiselleştirme notu eklenmeli.',
            ],
            [
                'title_suggestion' => 'Özel Günlerde Kıyafet Seçimi: Düğün davetiyesi ve kokteyl kodları',
                'topic_category' => BriefTopicCategory::WomensFashion,
                'target_audience' => 'Davetiye dress code’u okuyan kadın okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Yaygın davet kodlarının anlamı ve uygun uzunluk, kumaş ve aksesuar seçimi. Gizli reklam veya sponsorlu ürün yok.',
                'subheadings' => "- Dress code terimleri\n- Kokteyl ve gece davetleri\n- Gündüz düğün uyumu\n- Ayakkabı ve çanta dengesi\n- Son dakika alternatifleri",
                'suggested_internal_links' => "/yazilar\n/kategori/kadin-modasi",
                'cover_image_note' => 'Farklı davet stillerini temsil eden kombinler',
                'planned_publish_date' => '2026-09-02',
                'status' => BriefStatus::Idea,
                'notes' => 'Kültürel hassasiyetlere dikkat.',
            ],
            [
                'title_suggestion' => 'Erkekler İçin Temel Gardırop: İş ve günlük hayat dengesi',
                'topic_category' => BriefTopicCategory::MensFashion,
                'target_audience' => 'Gardırobunu sadeleştirmek isteyen erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Erkek gardırobunda minimum ama esnek parça seti: gömlek, pantolon, triko, dış giyim ve ayakkabı. Ürün satışı yok.',
                'subheadings' => "- Temel parça envanteri\n- Renk paleti önerisi\n- İş ve hafta sonu geçişi\n- Bakım rutini\n- Yatırım parçası nasıl seçilir",
                'suggested_internal_links' => "/yazilar\n/kategori/erkek-modasi",
                'cover_image_note' => 'Erkek gardırop askı düzeni',
                'planned_publish_date' => '2026-07-20',
                'status' => BriefStatus::Preparing,
                'notes' => 'Tek tip erkek silueti dayatılmamalı.',
            ],
            [
                'title_suggestion' => 'İş Görüşmesinde Erkek Kombini: Sade ve güven veren görünüm',
                'topic_category' => BriefTopicCategory::MensFashion,
                'target_audience' => 'İş görüşmesine girecek erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Takım elbise zorunluluğu olmadan, sektöre uygun erkek iş görünümü rehberi. Finansal veya hukuki tavsiye içermez.',
                'subheadings' => "- Sektör analizi\n- Gömlek ve pantolon uyumu\n- Ayakkabı ve kemer\n- Bakım detayları\n- Görüşme günü kontrol listesi",
                'suggested_internal_links' => "/yazilar\n/kategori/erkek-modasi",
                'cover_image_note' => 'Ofis ortamında sade erkek kombin',
                'planned_publish_date' => '2026-07-28',
                'status' => BriefStatus::Idea,
                'notes' => 'Marka logolu ürün görseli kullanılmamalı.',
            ],
            [
                'title_suggestion' => 'Erkek Casual Stil: Hafta sonu için katmanlı kombinler',
                'topic_category' => BriefTopicCategory::MensFashion,
                'target_audience' => 'Günlük stilini geliştirmek isteyen erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Katmanlama, renk uyumu ve rahat kalıp seçimiyle hafta sonu kombinleri. Sponsorlu ürün yok.',
                'subheadings' => "- Katmanlama temelleri\n- Jean ve chino dengesi\n- Triko ve sweatshirt\n- Ayakkabı eşleştirme\n- Mevsim geçişi",
                'suggested_internal_links' => "/yazilar\n/kategori/erkek-modasi",
                'cover_image_note' => 'Katmanlı casual erkek kombin, sokak stili',
                'planned_publish_date' => '2026-08-14',
                'status' => BriefStatus::Review,
                'notes' => 'Aşırı trend vurgusu yapılmamalı.',
            ],
            [
                'title_suggestion' => 'Erkek Dış Giyim Rehberi: Mont, kaban ve yağmurluk seçimi',
                'topic_category' => BriefTopicCategory::MensFashion,
                'target_audience' => 'Mevsimlik dış giyim alacak erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'İklim ve kullanım senaryosuna göre dış giyim türleri. Tek doğru cevap yerine karar ağacı sunulacak.',
                'subheadings' => "- Dış giyim türleri\n- Isı ve su geçirmezlik\n- Kesim ve omuz yapısı\n- Renk ve kombinlenebilirlik\n- Bakım ve depolama",
                'suggested_internal_links' => "/yazilar\n/kategori/erkek-modasi",
                'cover_image_note' => 'Üç farklı dış giyim türü yan yana',
                'planned_publish_date' => '2026-08-21',
                'status' => BriefStatus::Idea,
                'notes' => 'Fiyat karşılaştırması yok.',
            ],
            [
                'title_suggestion' => 'Erkek Ayakkabı Bakımı: Deri ve süet için temel adımlar',
                'topic_category' => BriefTopicCategory::MensFashion,
                'target_audience' => 'Ayakkabı ömrünü uzatmak isteyen erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Deri ve süet ayakkabı temizliği, nem kontrolü ve saklama. Marka ürünü önerilmez.',
                'subheadings' => "- Malzeme ayrımı\n- Günlük temizlik\n- Deri nemlendirme\n- Süet fırçalama\n- Saklama aparatları",
                'suggested_internal_links' => "/yazilar\n/kategori/erkek-modasi\n/kategori/aksesuar",
                'cover_image_note' => 'Ayakkabı bakım seti flat lay',
                'planned_publish_date' => '2026-09-05',
                'status' => BriefStatus::Idea,
                'notes' => 'Kimyasal marka önerisi yok.',
            ],
            [
                'title_suggestion' => 'Günlük Kullanım İçin Doğru Ayakkabı Seçimi: Konfor ve stil dengesi',
                'topic_category' => BriefTopicCategory::Accessories,
                'target_audience' => 'Günlük yürüyüş ve iş arasında ayakkabı arayan okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Taban desteği, malzeme nefes alabilirliği ve kombin uyumu açısından günlük ayakkabı seçimi. Sağlık teşhisi veya ortopedik tavsiye yok.',
                'subheadings' => "- Günlük kullanım senaryoları\n- Malzeme ve taban yapısı\n- Renk ve gardırop uyumu\n- Bakım döngüsü\n- Satın alma öncesi deneme",
                'suggested_internal_links' => "/yazilar\n/kategori/aksesuar",
                'cover_image_note' => 'Farklı günlük ayakkabı türleri',
                'planned_publish_date' => '2026-07-16',
                'status' => BriefStatus::Preparing,
                'notes' => 'Tıbbi ayak sağlığı iddiası yok.',
            ],
            [
                'title_suggestion' => 'Aksesuar Kullanım Dengesi: Az ama etkili tamamlayıcılar',
                'topic_category' => BriefTopicCategory::Accessories,
                'target_audience' => 'Aksesuarla kombinini tamamlamak isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Takı, kemer, şal ve çanta ile kombini boğmadan tamamlama ilkeleri. Ürün satışı veya affiliate yok.',
                'subheadings' => "- Bir kombinde aksesuar limiti\n- Metal tonu uyumu\n- Çanta ölçeği ve siluet\n- Şal ve eşarp kullanımı\n- Gündüz–gece geçişi",
                'suggested_internal_links' => "/yazilar\n/kategori/aksesuar",
                'cover_image_note' => 'Ölçülü aksesuarlı kombin detayı',
                'planned_publish_date' => '2026-07-30',
                'status' => BriefStatus::Idea,
                'notes' => 'Aşırı mücevher veya lüks vurgusu yok.',
            ],
            [
                'title_suggestion' => 'Şapka ve Bere Seçimi: Yüz hattına ve mevsime göre rehber',
                'topic_category' => BriefTopicCategory::Accessories,
                'target_audience' => 'Baş aksesuarı kullanmak isteyen kadın ve erkek okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Şapka brim genişliği, bere dokusu ve yüz oranına göre seçim ipuçları. Marka önerisi yok.',
                'subheadings' => "- Şapka türleri\n- Bere ve kulaklık uyumu\n- Saç tipine göre kullanım\n- Mevsimsel malzeme\n- Kombin örnekleri",
                'suggested_internal_links' => "/yazilar\n/kategori/aksesuar",
                'cover_image_note' => 'Farklı şapka türleri askıda',
                'planned_publish_date' => '2026-08-09',
                'status' => BriefStatus::Review,
                'notes' => 'Kültürel stereotip içermemeli.',
            ],
            [
                'title_suggestion' => 'Güneş Gözlüğü Seçimi: Çerçeve formu ve lens rengi temelleri',
                'topic_category' => BriefTopicCategory::Accessories,
                'target_audience' => 'Güneş gözlüğü alırken kararsız kalan okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Yüz formu ve çerçeve oranı eşleştirmesi, UV koruma etiketi okuma. Tıbbi göz sağlığı tavsiyesi verilmez.',
                'subheadings' => "- Yüz formu tipleri\n- Çerçeve ölçüsü\n- Lens renkleri ve kullanım\n- UV koruma etiketi\n- Saklama ve temizlik",
                'suggested_internal_links' => "/yazilar\n/kategori/aksesuar",
                'cover_image_note' => 'Çerçeve şekilleri infografik',
                'planned_publish_date' => '2026-08-23',
                'status' => BriefStatus::Idea,
                'notes' => 'Optik muayene yerine geçmez notu eklenmeli.',
            ],
            [
                'title_suggestion' => 'Çanta Organizasyonu: Günlük çanta içi düzen ve minimal taşıma',
                'topic_category' => BriefTopicCategory::Accessories,
                'target_audience' => 'Çanta içini düzenlemek isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Günlük ihtiyaç listesi çıkararak çanta hacmini optimize etme. Organizasyon ürünü satışı yok.',
                'subheadings' => "- Günlük zorunlu eşya listesi\n- Bölmelendirme\n- Ağırlık dağılımı\n- Mevsimsel içerik değişimi\n- Temizlik rutini",
                'suggested_internal_links' => "/yazilar\n/kategori/aksesuar",
                'cover_image_note' => 'Düzenli çanta içi flat lay',
                'planned_publish_date' => '2026-09-08',
                'status' => BriefStatus::Idea,
                'notes' => 'Belirli marka organizer önerilmez.',
            ],
            [
                'title_suggestion' => 'İlkbahar–Yaz Geçişinde Gardırop Rotasyonu',
                'topic_category' => BriefTopicCategory::SeasonTrends,
                'target_audience' => 'Mevsim değişiminde dolabını güncelleyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Kış parçalarını kaldırırken yazlık parçaları öne alma ve ara mevsim katmanları. Trend listesi değil, pratik geçiş rehberi.',
                'subheadings' => "- Depolama hazırlığı\n- Ara mevsim katmanları\n- Renk paleti güncellemesi\n- Ayakkabı rotasyonu\n- Kontrol listesi",
                'suggested_internal_links' => "/yazilar\n/kategori/sezon-trendleri",
                'cover_image_note' => 'İlkbahar renklerinde askı düzeni',
                'planned_publish_date' => '2026-03-10',
                'status' => BriefStatus::Completed,
                'notes' => 'Mikro trend listesi eklenmemeli.',
            ],
            [
                'title_suggestion' => 'Sonbahar–Kış Geçişinde Katmanlı Giyim Stratejileri',
                'topic_category' => BriefTopicCategory::SeasonTrends,
                'target_audience' => 'Soğuyan havada katman giyinmek isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Termal taban, orta katman ve dış kabuk mantığıyla mevsim geçişi. Hava durumuna göre esnek kombin önerileri.',
                'subheadings' => "- Üç katman kuralı\n- Malzeme seçimi\n- Renk koyulaştırma\n- Aksesuar ile ısı yönetimi\n- Günlük çıkış planı",
                'suggested_internal_links' => "/yazilar\n/kategori/sezon-trendleri",
                'cover_image_note' => 'Katmanlı sonbahar kombin',
                'planned_publish_date' => '2026-09-15',
                'status' => BriefStatus::Preparing,
                'notes' => 'Pahalı outdoor marka vurgusu yok.',
            ],
            [
                'title_suggestion' => 'Yazlık Kumaş Rehberi: Sıcak günlerde nefes alan kombinler',
                'topic_category' => BriefTopicCategory::SeasonTrends,
                'target_audience' => 'Yaz aylarında rahat giyinmek isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Keten, pamuk ve hafif karışımlarla sıcak hava kombinleri. Sağlık veya güneş yanığı tavsiyesi ayrı konu.',
                'subheadings' => "- Nefes alan kumaşlar\n- Açık renk paleti\n- Bol ve dar kesim dengesi\n- Ayakkabı ve çorap\n- Akşam serinlemesi katmanı",
                'suggested_internal_links' => "/yazilar\n/kategori/sezon-trendleri",
                'cover_image_note' => 'Yazlık keten kombin, doğal ışık',
                'planned_publish_date' => '2026-05-20',
                'status' => BriefStatus::Completed,
                'notes' => 'Plaj modası odaklı olmamalı; günlük yaşam ağırlıklı.',
            ],
            [
                'title_suggestion' => 'Kış Aksesuarları: Atkı, eldiven ve bere uyumu',
                'topic_category' => BriefTopicCategory::SeasonTrends,
                'target_audience' => 'Kış aylarında aksesuar kombinleyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Kış aksesuarlarını tek palet altında birleştirme ve malzeme seçimi. Marka önerisi yok.',
                'subheadings' => "- Renk ve doku uyumu\n- Malzeme ve alerji notu\n- Eldiven ve cep uyumu\n- Atkı bağlama stilleri\n- Bakım ve depolama",
                'suggested_internal_links' => "/yazilar\n/kategori/sezon-trendleri\n/kategori/aksesuar",
                'cover_image_note' => 'Koordineli kış aksesuar seti',
                'planned_publish_date' => '2026-11-01',
                'status' => BriefStatus::Idea,
                'notes' => 'Alerji uyarısı genel tutulmalı.',
            ],
            [
                'title_suggestion' => 'Resmi Sezon Trendlerini Okumak: Abartmadan gardıroba uyarlamak',
                'topic_category' => BriefTopicCategory::SeasonTrends,
                'target_audience' => 'Trendleri takip eden ama aşırı tüketmek istemeyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Podyum ve perakende trendlerini eleştirel okuma ve mevcut dolaba küçük dokunuşlarla uyarlama. Kaynak gösterimi zorunlu.',
                'subheadings' => "- Trend vs. klasik\n- Mikro trend tanıma\n- Bütçe dostu uyarlama\n- Renk ve kesim denemesi\n- Ne zaman trendi geçmek",
                'suggested_internal_links' => "/yazilar\n/kategori/sezon-trendleri",
                'cover_image_note' => 'Trend parça + klasik parça yan yana',
                'planned_publish_date' => '2026-09-22',
                'status' => BriefStatus::Review,
                'notes' => 'Doğrulanmamış trend iddiası yok; kaynak şart.',
            ],
            [
                'title_suggestion' => 'Sürdürülebilir Alışveriş: Bilinçli parça seçimi ve uzun ömür',
                'topic_category' => BriefTopicCategory::SustainableFashion,
                'target_audience' => 'Daha az ama daha iyi alışveriş yapmak isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Hızlı moda döngüsüne alternatif olarak parça başına maliyet, kullanım sıklığı ve bakım odaklı alışveriş çerçevesi. Doğrulanmamış çevre iddiası yok.',
                'subheadings' => "- İhtiyaç vs. istek ayrımı\n- Kalite kontrol soruları\n- İkinci el ve tamir\n- Etiket okuma (genel)\n- Alışveriş öncesi 24 saat kuralı",
                'suggested_internal_links' => "/yazilar\n/kategori/surdurulebilir-moda",
                'cover_image_note' => 'Uzun ömürlü parçalar ve bakım kiti',
                'planned_publish_date' => '2026-07-12',
                'status' => BriefStatus::Preparing,
                'notes' => 'Greenwashing örnekleri abartılmadan anlatılmalı.',
            ],
            [
                'title_suggestion' => 'Gardırobunuzda Sürdürülebilir Bakım Rutini Oluşturma',
                'topic_category' => BriefTopicCategory::SustainableFashion,
                'target_audience' => 'Giysi ömrünü uzatarak atığı azaltmak isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Yıkama sıklığı, onarım ve yeniden kombinleme ile sürdürülebilir bakım planı. Ürün satışı yok.',
                'subheadings' => "- Yıkama azaltma yöntemleri\n- Küçük onarımlar\n- Leke müdahalesi\n- Depolama ve güve önleme\n- Aylık bakım takvimi",
                'suggested_internal_links' => "/yazilar\n/kategori/surdurulebilir-moda",
                'cover_image_note' => 'Onarım malzemeleri ve iğne iplik',
                'planned_publish_date' => '2026-08-02',
                'status' => BriefStatus::Idea,
                'notes' => 'Kimyasal formül paylaşılmamalı.',
            ],
            [
                'title_suggestion' => 'İkinci El Alışveriş Rehberi: Kontrol listesi ve hijyen',
                'topic_category' => BriefTopicCategory::SustainableFashion,
                'target_audience' => 'Vintage ve ikinci el düşünen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'İkinci el parça seçerken kalite, ölçü ve hijyen kontrolü. Belirli platform veya mağaza linki yok.',
                'subheadings' => "- Nerede aramalı (genel kategoriler)\n- Kumaş ve dikiş kontrolü\n- Ölçü ve esneme\n- Temizlik sonrası kullanım\n- Kombinlenebilirlik testi",
                'suggested_internal_links' => "/yazilar\n/kategori/surdurulebilir-moda",
                'cover_image_note' => 'İkinci el askıda seçim anı',
                'planned_publish_date' => '2026-08-16',
                'status' => BriefStatus::Review,
                'notes' => 'Affiliate veya mağaza promosyonu yok.',
            ],
            [
                'title_suggestion' => 'Tekstil Etiketleri ve Şeffaflık: Okuyucuya ne söylenmeli?',
                'topic_category' => BriefTopicCategory::SustainableFashion,
                'target_audience' => 'Sürdürülebilirlik iddialarını sorgulayan okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Yaygın sürdürülebilirlik etiketlerinin anlamı ve sınırları. Doğrulanmamış iddia kullanılmayacak; kaynak zorunlu.',
                'subheadings' => "- Organik, geri dönüştürülmüş terimleri\n- Sertifika logoları (genel)\n- Greenwashing işaretleri\n- Okuyucuya pratik sorular\n- Kaynak gösterme",
                'suggested_internal_links' => "/yazilar\n/kategori/surdurulebilir-moda",
                'cover_image_note' => 'Etiket yakın planı, nötr',
                'planned_publish_date' => '2026-08-30',
                'status' => BriefStatus::Idea,
                'notes' => 'Hukuki yorum yok; genel bilgilendirme.',
            ],
            [
                'title_suggestion' => 'Kapsül Gardırop ve Sürdürülebilirlik: Az parça, çok kombin',
                'topic_category' => BriefTopicCategory::SustainableFashion,
                'target_audience' => 'Minimal ve sürdürülebilir yaşamı birleştirmek isteyen okurlar',
                'search_intent' => 'bilgilendirici',
                'content_summary' => 'Kapsül gardırop yaklaşımının atık azaltmaya katkısı ve bilinçli genişletme kuralları. Tüketim teşviki yok.',
                'subheadings' => "- Kapsül gardırop tanımı\n- Sürdürülebilirlik bağlantısı\n- Parça ekleme kuralları\n- Mevsimsel güncelleme\n- Uzun vadeli plan",
                'suggested_internal_links' => "/yazilar\n/kategori/surdurulebilir-moda\n/kategori/kadin-modasi",
                'cover_image_note' => 'Az parçalı sürdürülebilir gardırop',
                'planned_publish_date' => '2026-09-10',
                'status' => BriefStatus::Idea,
                'notes' => 'İki konuyu birleştirirken tekrar yapılmamalı.',
            ],
        ];
    }
}
